---
title: "DATS-6101-Project"
output: html_document
date: "`r Sys.Date()`"
---
``` {r, echo = TRUE}
#Install packages and load package.
install.packages('gssr', repos =
                   c('https://kjhealy.r-universe.dev', 'https://cloud.r-project.org'))
install.packages('gssrdoc', repos =
                   c('https://kjhealy.r-universe.dev', 'https://cloud.r-project.org'))
                   
library(gssr)
library(gssrdoc)


#NEW INFO

#Let's say we were going to compare a range of 1975 to 1980 to the data avalible in 2018. 
#We would need to call all of the years we will need. 

#Older years:
gss74 <- gss_get_yr(1974)
gss75 <- gss_get_yr(1975)
gss76 <- gss_get_yr(1976)
gss77 <- gss_get_yr(1977)
gss78 <- gss_get_yr(1978)
gss80 <- gss_get_yr(1980)

#Newer years:
gss16 <- gss_get_yr(2016)
gss18 <- gss_get_yr(2018)
gss21 <- gss_get_yr(2021)
gss22 <- gss_get_yr(2022)

#Check your data
gss74
gss75
gss76
gss77
gss78
gss80

gss16
gss18
gss21
gss22

#Now we need to find all common columns within the data sets. Variables that are not avalible in all 5 subsets will not transfer over, because in order to combine these tables, the colmuns need to match.
common_74_80 <- Reduce(intersect, list(colnames(gss74), colnames(gss75), colnames(gss76), colnames(gss77), colnames(gss78), colnames(gss80)))

common_16_22 <- Reduce(intersect, list(colnames(gss16), colnames(gss18), colnames(gss21), colnames(gss22)))                       

#Once we identify and lable the common columns, we can combine our tables using our new "common" value. 
gss74_80 <- rbind(gss74 [common_74_80], gss75 [common_74_80], gss76 [common_74_80], gss77 [common_74_80], gss78 [common_74_80], gss80 [common_74_80])

gss16_22 <- rbind(gss16 [common_16_22], gss18 [common_16_22], gss21 [common_16_22], gss22 [common_16_22])

#New datasets
gss74_80

gss16_22 

```


```{r}
gss74_80
gss16_22
```

```{r}
write.csv(gss74_80, 'gss_old.csv')
write.csv(gss16_22, 'gss_new.csv')
```